# numpy
get to the documentation [here](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [1]:
#import numpy
import numpy as np

## The Basics 

* Numpy dimensions are called __axes__. 
* example of 3D space that has one axis  [1, 3, 3] 
                            has two axes  [[1, 0, 0]
                                         [0, 2, 1]]
* Numpy's array is called `ndarray`.
* numpy.array are different from array.array 
* `ndarray` is an object and in the following examples we will discuss it's attributes

In [2]:
arr1d = np.arange(5).reshape(5,1)
print(arr1d)
arr1d = arr1d.reshape(5)
print(arr1d)

[[0]
 [1]
 [2]
 [3]
 [4]]
[0 1 2 3 4]


In [3]:
arr2d = np.arange(15).reshape(3,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

>__array.shape() returns the size of the array__


In [5]:
arr1d.shape

(5,)

In [6]:
arr2d.shape

(3, 5)

In [7]:
arr3d.shape

(3, 3, 3)

> __array.ndim returns the dimentions__

In [8]:
arr1d.ndim

1

In [9]:
arr2d.ndim

2

In [10]:
arr3d.ndim

3

> __dtype.name return the name of data type__

In [11]:
arr3d.dtype.name

'int32'

> __itemsize__

In [12]:
arr1d.itemsize

4

In [13]:
arr2d.itemsize

4

In [14]:
arr3d.itemsize

4

> size returns number of data in array

In [15]:
arr1d.size

5

In [16]:
arr2d.size

15

In [17]:
arr3d.size

27

> __type returns object type__

In [18]:
type(arr1d)

numpy.ndarray

In [19]:
type(arr2d)

numpy.ndarray

---


### Array creation
